project:
  name: "OriLibre - Japan"
  description: "Hybrid style for Japan orienteering map"
map:
  center: [139.3127,35.8855]
  zoom: 15
  bearing: 0
  pitch: 0
resources:
  design-plan:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/projects/isomized-japan/design-plan.yml"
  symbol-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/symbol-palette.yml"
  color-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/color-palette.yml"
  image-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/image-palette.yml"
