project:
  name: "OpenFreeMap to ISOM2017-2"
  description: "OpenFreeMap to ISOM2017-2"

resources:
  design-plan:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/projects/global/design-plan.yml"
  symbol-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/symbol-palette.yml"
  color-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/color-palette.yml"
  image-palette:
    file: "https://cdn.jsdelivr.net/gh/tjmsy/isomizer-projectfiles@0.3/palettes/isom2017/image-palette.yml"
